version: "2"

services:
  app:
    image: "klokantech/$PACKAGE_NAME:$PACKAGE_VERSION"
    container_name: com.klokantech.skeleton
    command: >
        /venv/bin/uwsgi
        --master
        --uid nobody
        --enable-threads
        --socket 0.0.0.0:8000
        --wsgi $PACKAGE_NAME:app
    restart: always
    environment:
      - FLASK_SECRET_KEY="<<< Production key >>>"
  nginx:
    image: klokantech/nginx
    ports:
      - "8000:80"
    links:
      - app
    volumes:
      - ./nginx:/etc/nginx/conf.d
