version: "2"

services:
  app:
    build:
      context: ./app
      args:
        - VERSION=$VERSION
        - SETUP_MODE=$SETUP_MODE
    command: /venv/bin/python -m skeleton runserver  # __NAME__
    volumes:
      - ./app/skeleton:/venv/app/skeleton  # __NAME__
    ports:
      - "8000:8000"
    environment:
      - FLASK_DEBUG=true
      - FLASK_DEVELOPMENT=true
      - FLASK_SECRET_KEY="<<< Development key >>>"
